# Slot Types
HEAD_SLOT = 'Head'
BODY_SLOT = 'Body'
LEGS_SLOT = 'Legs'
BOOTS_SLOT = 'Boots'
ONE_HANDED_SLOT = 'One Handed'
TWO_HANDED_SLOT = 'Two Handed'
COIN_SLOT = 'Coin'
MISC_SLOT = 'Miscellaneous'

# Coin Value
COPPER_VALUE = 1
SILVER_VALUE = 10
GOLD_VALUE = 100
PLATINUM_VALUE = 1000

LOW_PURITY = 1
HIGH_PURITY = 5